### ISSUE TITLE
export doesn't do anything for me on 2021.2.2

### ISSUE THREAD

**Issue by ioweb-gr** [shiraji/plugin-importer-exporter#16]
I click on export button but nothing happens.

**Comment by Guizrio** [comment]
Hello,
Same for me, nothing happens (no message appears). 
Note that an error is produced in idea.log when i click on the "Export" button. The log produced is :  

2021-11-26 12:12:33,363 [3094964]  ERROR - llij.ide.plugins.PluginManager - 'com.intellij.openapi.extensions.PluginId[] com.intellij.ide.plugins.IdeaPluginDescriptor.getDependentPluginIds()'
java.lang.NoSuchMethodError: 'com.intellij.openapi.extensions.PluginId[] com.intellij.ide.plugins.IdeaPluginDescriptor.getDependentPluginIds()'
        at com.github.shiraji.pluginimporterexporter.model.PluginNodeEntity.newInstance(PluginNodeEntity.java:42)
        at com.github.shiraji.pluginimporterexporter.model.PluginNodeModelFactory.newInstance(PluginNodeModelFactory.java:17)
        at com.github.shiraji.pluginimporterexporter.action.PluginExporterAction.writePluginInfo(PluginExporterAction.java:127)
        at com.github.shiraji.pluginimporterexporter.action.PluginExporterAction.access$500(PluginExporterAction.java:23)
        at com.github.shiraji.pluginimporterexporter.action.PluginExporterAction$1.doExport(PluginExporterAction.java:83)
        at com.github.shiraji.pluginimporterexporter.action.PluginExporterAction$1.run(PluginExporterAction.java:55)
        at com.intellij.openapi.ui.DialogBuilder$MyDialogWrapper.doOKAction(DialogBuilder.java:429)
        at com.intellij.openapi.ui.DialogWrapper$OkAction.doAction(DialogWrapper.java:1915)
        at com.intellij.openapi.ui.DialogWrapper$DialogWrapperAction.actionPerformed(DialogWrapper.java:1868)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:270)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
        at java.desktop/java.awt.Component.processEvent(Component.java:6417)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1063)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:699)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:435)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1726)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1685)
        at com.intellij.openapi.ui.DialogBuilder.showImpl(DialogBuilder.java:77)
        at com.intellij.openapi.ui.DialogBuilder.show(DialogBuilder.java:44)
        at com.github.shiraji.pluginimporterexporter.action.PluginExporterAction.actionPerformed(PluginExporterAction.java:33)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:240)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:261)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:240)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:248)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:236)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:67)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:240)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:90)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:90)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:515)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:545)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
        at java.desktop/java.awt.Component.processEvent(Component.java:6417)
        at java.desktop/java.awt.Container.processEvent(Container.java:2263)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
        at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:814)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:751)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
        at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2021-11-26 12:12:33,364 [3094965]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2021.2.2  Build #IU-212.5284.40
2021-11-26 12:12:33,364 [3094965]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.12; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2021-11-26 12:12:33,364 [3094965]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10
2021-11-26 12:12:33,364 [3094965]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Plugin Importer+Exporter version: 0.0.3
2021-11-26 12:12:33,364 [3094965]  ERROR - llij.ide.plugins.PluginManager - Last Action: PluginExporterAction

**Comment by Remigius2011** [comment]
did anybody try this fork: https://github.com/ziscloud/plugin-importer-exporter/commits/master? meanwhile, I have synced the plugins manually, it did work.

**Comment by dorb4r** [comment]
Not working for me either
